apiVersion: apps/v1
kind: Deployment
metadata:
  name: librum
  namespace: librum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librum
  template:
    metadata:
      labels:
        app: librum
    spec:
      containers:
      - name: librum
        image: ghcr.io/librum-reader/librum-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: JWTValidIssuer
          value: "exampleIssuer"
        - name: JWTValidIssuer
          value: "exampleIssuer"
        - name: DBConnectionString
          value: "Server=mariadb;port=3306;Database=librum;Uid=librum;Pwd=mariadb;"
        # Add the rest of your environment variables here
        volumeMounts:
        - name: librum-storage
          mountPath: /var/lib/librum-server/librum_storage
      volumes:
      - name: librum-storage
        hostPath:
          path: /data-nfs/librum/data
