---
apiVersion: v1
kind: Service
metadata:
  name: librum
  namespace: librum
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.23.31
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: librum